### ISSUE TITLE
[Bug] [1.18.2]: Too many break particles 

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Fuzss/diagonal-blocks#22] opened 2022-07-31 12:53 UTC
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

v3.1.0

### Notes (Required)

Current behaviour: When you break a diagonal fence, way more break particles appear as compared to break particles from a "normal" fence (see image).
![2022-07-29_18 19 36](https://user-images.githubusercontent.com/72312697/182027241-f0b7800d-7cc1-47fb-a080-c0c24fe8c598.png)

Steps to reproduce;
1, Open up a world with Diagonal Fences installed.
2. Place down a diagonal fence by placing two fences diagonally.
3. Break it and observe the difference between the particles coming from the vanilla fence and the diagonal fence.

Expected behaviour: The diagonal fence's break particles should be in-line with the "normal" amount of break particles occurring from the vanilla fences.

### latest.log (Optional)

https://gist.github.com/GeorgeOrwell1/0c4db3716169e9aa4f29aad2a4b35794

**Comment by XFactHD** [comment] 2022-07-31 13:02
This is caused by Minecraft calculating the amount of particles from the amount of collision boxes the block has. The normal fence only has a maximum of 3 or 5 collision boxes with all four arms. A single diagonal fence arm has a lot more than that to make the diagonal surface feel as smooth as possible.
This may not be fixable.

**Comment by GeorgeOrwell1** [comment] 2022-07-31 13:29
Oooh okay, I understand.

**Comment by Fuzss** [comment] 2022-08-01 10:29
Fixed in v4.1.0 for Minecraft 1.19.1.

**Closed as completed by Fuzss** 2022-08-01 10:29 UTC
Labels: bug
